### ISSUE TITLE
onepage didn't prevent alternating margins

### ISSUE THREAD

**Issue by olearydj** [nmfs-opensci/quarto_titlepages_v1#2]
### Description

Hello again. Same disclaimer and appreciation applies.

When using `academic-static` for a pdf based on the `scrbook` document class, the class option `onepage` doesn't seem to suppress alternating margins as I believe you claim. Using `twoside=false` does the trick, per <https://tex.stackexchange.com/a/18791/286622>.

I'm not sure if this is a change in LaTeX, my own misunderstanding, or a failure or Quarto to properly process the `onepage` option. 

### Steps to Reproduce
Render the attached Quarto document (same as in prior bug report) with `onepage` or `twoside=false` in `classoption` as described above.
[test_font.zip](https://github.com/nmfs-opensci/quarto_titlepages_v1/files/10220041/test_font.zip)

**Comment by eeholmes** [comment]
Thx for the heads up, I had the wrong classoptions. Should be
```
    classoption: ["oneside", "open=any"]
```
Fixing now.

**Comment by eeholmes** [comment]
Fixed.
